name: Render RMarkdown

on:
  push:
    paths:
      - '**.Rmd' # Only run when Rmd files change

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Essential for pushing changes back
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install packages
        run: |
          install.packages(c("rmarkdown", "tidyverse", "ggplot2", "broom", "plotly")) # Add other packages you use here
        shell: Rscript {0}

      - name: Render RMarkdown
        run: |
          rmarkdown::render("src/trabalho.Rmd", output_file = "AnaliseCrimesSp.html") # CHANGE THIS to your filename
        shell: Rscript {0}

      - name: Commit and Push HTML
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto-render Rmd to HTML
          file_pattern: '*.html'